parameters:
  werkint_command.stuff.class:
    Werkint\Bundle\CommandBundle\Service\Processor\Stuff\StuffProcessor
  werkint_command.stuff.locks.class:
    Werkint\Bundle\CommandBundle\Service\Processor\Stuff\Locks
  werkint_command.stuff.compileprovider.class:
    Werkint\Bundle\CommandBundle\Service\Processor\Stuff\CompileProvider
  werkint_command.compile.class:
    Werkint\Bundle\CommandBundle\Service\Processor\Compile\CompileProcessor

services:
  # Задачи по crond
  werkint_command.stuff:
    class: %werkint_command.stuff.class%
    arguments:
      - @werkint_mutex.mutexmanager
      - @werkint_command.stuff.locks
  werkint_command.stuff.locks:
    class: %werkint_command.stuff.locks.class%
  werkint_command.stuff.compileprovider:
    class: %werkint_command.stuff.compileprovider.class%
    arguments:
      - @werkint_command.stuff
    tags:
      - { name: werkint_command.compile, class: werkint_command.stuff, priority: -100 }

  # Компиляция ресурсов
  werkint_command.compile:
    class: %werkint_command.compile.class%
